apiVersion: v1
kind: Service
metadata:
  name: flask-service
  labels:
    app: flask-monitoring
spec:
  selector:
    app: flask-monitoring
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: ClusterIP
